# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 14:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmark', '0002_auto_20171001_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='client_name',
        ),
        migrations.AddField(
            model_name='data',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
